global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'docker-host-alpha'

remote_write:
  - url: "http://192.168.50.2:8086/api/v1/prom/write?db=prometheus"
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'job_instance:.*'
        action: keep

  - url: "http://192.168.50.2:8087/api/v1/prom/write?db=prometheus"
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'job_container:.*'
        action: keep

scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.50.2:9100', '192.168.50.3:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.50.2:8080', '192.168.50.3:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
